# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - shawnprod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://end2endprod.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e8ea269a6a204639af9d38e23fdcbfa6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_23819097184646ef95d29a763e2e2bf8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: end2endprod.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e8ea269a6a204639af9d38e23fdcbfa6 }}/mltest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'shawnprod'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8d1d566acdf34c54be06e2e14ae39ecb }}
        images: 'end2endprod.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e8ea269a6a204639af9d38e23fdcbfa6 }}/mltest:${{ github.sha }}'